id: ltw_be
name: Abgeordnetenhauswahl Berlin 2026
hashtag: "#aghwahl"

scraper:
  function: scrape_ltw
  url: https://www.wahlrecht.de/umfragen/landtage/berlin.htm
  ind_row_remove: [1, 2]

parliament:
  seats: 130
  majority: 66
  hurdle: 0.05
  seat_allocation: hare_niemeyer

pooling:
  period: 14
  period_extended: 28

parties:
  - id: cdu
    label: Union
    color: "#000000"
    required: true
  - id: spd
    label: SPD
    color: "#E3000F"
    required: true
  - id: greens
    label: Grüne
    color: "#46962b"
    required: true
  - id: afd
    label: AfD
    color: "#82caff"
    required: true
  - id: left
    label: Linke
    color: "#ff1493"
    required: false
  - id: fdp
    label: FDP
    color: "#ffed00"
    required: false
  - id: bsw
    label: BSW
    color: "#6d1f99"
    required: false
  - id: others
    label: Sonstige
    color: "#808080"
    required: false

pollsters:
  - allensbach
  - civey
  - emnid
  - forsa
  - fgw
  - gms
  - infratest
  - insa

coalitions:
  # 2-party coalitions
  - parties: [cdu, spd]
    label: "Union-SPD"
    color: "#000000"
  - parties: [spd, cdu]
    label: "SPD-Union"
    color: "#E3000F"
  - parties: [cdu, greens]
    label: "Union-Grüne"
    color: "#000000"
  - parties: [greens, cdu]
    label: "Grüne-Union"
    color: "#46962b"
  - parties: [spd, greens]
    label: "SPD-Grüne"
    color: "#E3000F"
  - parties: [greens, spd]
    label: "Grüne-SPD"
    color: "#46962b"
  - parties: [afd, cdu]
    label: "AfD-Union"
    color: "#82caff"
  - parties: [cdu, afd]
    label: "Union-AfD"
    color: "#000000"
  - parties: [afd, spd]
    label: "AfD-SPD"
    color: "#82caff"
  - parties: [spd, afd]
    label: "SPD-AfD"
    color: "#E3000F"
  # 3-party coalitions
  - parties: [cdu, spd, greens]
    label: "Union-SPD-Grüne"
    color: "#000000"
  - parties: [spd, cdu, greens]
    label: "SPD-Union-Grüne"
    color: "#E3000F"
  - parties: [greens, cdu, spd]
    label: "Grüne-Union-SPD"
    color: "#46962b"
  - parties: [cdu, greens, fdp]
    label: "Union-Grüne-FDP"
    color: "#000000"
  - parties: [greens, cdu, fdp]
    label: "Grüne-Union-FDP"
    color: "#46962b"
  - parties: [fdp, cdu, greens]
    label: "FDP-Union-Grüne"
    color: "#ffed00"
  - parties: [cdu, spd, fdp]
    label: "Union-SPD-FDP"
    color: "#000000"
  - parties: [spd, cdu, fdp]
    label: "SPD-Union-FDP"
    color: "#E3000F"
  - parties: [fdp, cdu, spd]
    label: "FDP-Union-SPD"
    color: "#ffed00"
  - parties: [spd, greens, left]
    label: "SPD-Grüne-Linke"
    color: "#E3000F"
  - parties: [greens, spd, left]
    label: "Grüne-SPD-Linke"
    color: "#46962b"
  - parties: [left, spd, greens]
    label: "Linke-SPD-Grüne"
    color: "#ff1493"
  - parties: [spd, greens, fdp]
    label: "SPD-Grüne-FDP"
    color: "#E3000F"
  - parties: [greens, spd, fdp]
    label: "Grüne-SPD-FDP"
    color: "#46962b"
  - parties: [fdp, spd, greens]
    label: "FDP-SPD-Grüne"
    color: "#ffed00"
  # AfD majority
  - parties: [afd]
    label: "AfD"
    color: "#82caff"

analyses:
  biggest_party:
    - parties: [cdu, spd, greens, left, afd]
      label: "Wer wird stärkste Kraft?"
  pass_hurdle:
    parties: [fdp, bsw]
    label: "Schaffen es die folgenden Parteien in den Landtag?"
